[package]
name = "common-range-tools"
version = "0.1.0"
edition = "2024"
license = "MIT"
homepage = "https://github.com/akalinux/r-span-tools"
repository = "https://github.com/akalinux/r-span-tools"
description = "Library to find Common Range Intersections"
readme = "README.md"
license-file = "LICENSE"
keywords = ["range","intersection","common"]
categories = ["algorithms","data-structures","science"]
